site_name: COMPAS FEA2
site_url: https://github.com/compas-dev/compas_fea2

repo_url: https://github.com/compas-dev/compas_fea2

extra:
  homepage: https://compas-dev.github.io/compas_fea2/

extra_css:
  - stylesheets/compas.css

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/compas_icon_white.png
  favicon: images/favicon.ico
  features:
    - content.code.copy
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - callouts:
      strip_period: no
  - footnotes
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: "Â¤"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]  # search packages in the src folder
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://compas.dev/compas/latest/objects.inv
          options:
            allow_inspection: true
            backlinks: tree
            docstring_options:
              ignore_init_summary: true
              trim_doctest_flags: true
            docstring_style: numpy
            docstring_section_style: table
            filters: public
            group_by_category: true
            heading_level: 1
            inheritance_diagram_direction: TD
            inherited_members: false
            line_length: 88
            merge_init_into_class: true
            modernize_annotations: true
            parameter_headings: false
            preload_modules: [mkdocstrings,compas]
            relative_crossrefs: true
            scoped_crossrefs: true
            separate_signature: true
            show_bases: false
            show_category_heading: true
            show_docstring_attributes: true
            show_docstring_functions: true
            show_docstring_modules: false
            show_if_no_docstring: false
            show_inheritance_diagram: false
            show_root_heading: true
            show_root_full_path: true
            show_signature: true
            show_signature_annotations: true
            show_signature_type_parameters: true
            show_source: false
            show_submodules: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary:
              modules: false
            type_parameter_headings: true
            unwrap_annotated: true

nav:
  - Home: index.md
  - Get Started:
    - Introduction: introduction.md
    - Installation: installation.md
    - Model: model.md
    - Problem: problem.md
    - Solver: solver.md
    - Results: results.md
  - Guide:
    - guide/index.md
  - API:
    - compas_fea2.backends: api/compas_fea2.backends.md
    - compas_fea2.base: api/compas_fea2.base.md
    - compas_fea2.cli: api/compas_fea2.cli.md
    - compas_fea2.config: api/compas_fea2.config.md
    - compas_fea2.job: api/compas_fea2.job.md
    - compas_fea2.model: api/compas_fea2.model.md
    - compas_fea2.problem: api/compas_fea2.problem.md
    - compas_fea2.registration: api/compas_fea2.registration.md
    - compas_fea2.results: api/compas_fea2.results.md
    - compas_fea2.units: api/compas_fea2.units.md
    - compas_fea2.utilities: api/compas_fea2.utilities.md
  - Examples:
    - examples/index.md
